=== HCHexY/DAW2020/TPC2/ProjectRecord.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT projectRecord (header, workteam, abstract, footer)>


<!ELEMENT header (dates,titles, supervisor)>
<!ELEMENT titles (bigTitle,keyName,title,subtitle)>
<!ELEMENT bigTitle (#PCDATA)>
<!ELEMENT keyName (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT subtitle (#PCDATA)>

<!ELEMENT supervisor (#PCDATA)>
<!ELEMENT dates EMPTY>
<!ATTLIST dates begin CDATA #REQUIRED
                end CDATA #REQUIRED>
<!ATTLIST supervisor svRef CDATA #REQUIRED>

<!ATTLIST projectRecord id ID #REQUIRED>


<!ELEMENT workteam (teammate+)>
<!ELEMENT teammate (#PCDATA)>
<!ATTLIST teammate 
    tmmRef CDATA #REQUIRED
    numMecan CDATA #IMPLIED>

<!ELEMENT abstract (p+)>
<!ELEMENT p (#PCDATA|i|b|u|ref|br)* >
<!ELEMENT i (#PCDATA|p|b|u|ref|br)*>
<!ELEMENT b (#PCDATA|i|p|u|ref|br)*>
<!ELEMENT u (#PCDATA|i|b|p|ref|br)*>
<!ELEMENT br EMPTY >
<!ELEMENT ref (#PCDATA|i|b|u)*>
<!ATTLIST ref link CDATA #REQUIRED
              type CDATA #REQUIRED>
<!ATTLIST p sizePriority CDATA "5" >
<!ELEMENT footer (deliverables?,pubDate)>
<!ELEMENT deliverables (ref+)>
<!ELEMENT pubDate (#PCDATA)>

=== HCHexY/DAW2020/TPC2/ProjectRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "ProjectRecord.dtd">
<projectRecord id="ID000">
    <header>
        <dates begin="21/10/2020" end="28/10/2020"/>
        <titles>
            <bigTitle>Project Record</bigTitle>
            <keyName>ProjecRecord</keyName>
            <title>Schema DTD para elaboração de Project Records em XML</title>
            <subtitle>Relatório inserido nos TPC's da unidade curricular de Desenvolvimento de Aplicações WEB</subtitle>
        </titles>
        <supervisor svRef="http://www.di.uminho.pt/~jcr">
            José Carlos Ramalho
        </supervisor>
    </header>
    <workteam>
        <teammate numMecan="A84657" tmmRef="a84656@alunos.uminho.pt">
            Hugo Manuel Cunha
        </teammate>
    </workteam>
    <abstract>
        <p>
            Este trabalho demonstra uma forma de utilizar a linguagem <b>XML</b> para desenvolver uma possivel 
            implementação de um ficheiro para armazenar e indexar teses e relatórios.       
        </p>
        <p>
            Foi produzido um ficheiro <i>DTD</i> descritivo da estrutura a adotar.<br/>
            Assim é possivel utilizar ferramentas para validar ou criar uma maquete de um ficheiro <b>XML</b> adequado.
        </p>
        <p>
            O esquema suporta um header com as datas de inicio e fim, titulos e um supervisor;<br/>
            Uma definição de equipa de trabalho com referencias de email dos colaboradores;<br/>
            Um abstrato capaz de representar diferentes formatações de texto como <b>bold</b>,<i>itálico</i>,<br/>
            <u>sublinhado</u> e quebras de linha em diferentes parágrafos com um possivel tamanho de letra proporcional á prioridade (5 por defeito);<br/>
            E um footer com zona para referências e anexos e data de publicação do documento.
        </p>
    </abstract>
    <footer>
        <deliverables>
            <ref link="ProjectRecord.dtd" type="DTD">
               Esquema do Relatório
            </ref>
            <ref link="ProjectRecord.xsd" type="XSD">
                XML Schema Definition utilizado para criar uma amostra a partir do DTD
            </ref>
            <ref link="instance1.xml" type="XML">
                Amostra gerada automaticamente do DTD 
            </ref>
        </deliverables>
        <pubDate>26/10/2020</pubDate>
    </footer>
</projectRecord>

=== HCHexY/DAW2020/TPC3/ProjectRecord.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projectRecord SYSTEM "../TPC2/ProjectRecord.dtd">
<projectRecord id="TPC3">
    <header>
        <dates begin="28/10/2020" end="4/11/2020"/>
        <titles>
            <bigTitle> Schemas para arquivo de Arqueossitios </bigTitle>
            <keyName> XSL e DTD para o dataset arq </keyName>
            <title>Arquivo de Arqueossitios</title>
            <subtitle>Schema DTD e XSLT para a validação e transformação do dataset arq</subtitle>
        </titles>
        <supervisor svRef="jcr@di.uminho.pt"></supervisor>
    </header>
    <workteam>
        <teammate tmmRef="a84656"> Hugo Manuel Cunha</teammate>
    </workteam>
    <abstract>
        <p sizePriority="2" >
            Este trabalho tem como objetivo criar um <i>schema</i> DTD para a validação de ficheiros com a mesma estrutura do <i>dataset</i> arq bem como 
            um ficheiro XSL para transformar os dados num site multi-pagina em HTML
        </p>
        <p>
            O <i>dataset</i> arq consiste num ficheiro XML com elementos <b>ARQELEM</b> onde cada um deste descreve um arqueossitio. <br/>
            Cada arqueossitio contém varios elementos descritivos da sua localização, interesse cultural e importância arqueológica bem como bibligrafia e outros
            elementos descritivos de pessoas contribuintes no estudo do mesmo arqueossitio.  
        </p>
        <p>
            Na geração do HTML tem-se em consideração a falta de <i>tags</i> opcionais, o agrupamento de <i>tags</i> semelhantes e uma estrutura adequada á apresentação
            intuitiva de um documento.
        </p>
        <p sizePriority="7">
            Nota1: Para a criação do ficheiro DTD primeiramente gerado automaticamente um ficheiro com recurso ás ferramentas do <i>Oxygen XML Editor</i> e de seguida
            foi tratado de forma critica para apresentar um ficheiro DTD de acordo com as capabilidades aprendidas nas aula.<br/>
            O objetivo era mapear todas as tags em primeiro lugar antes de desenvolver o schema.
            
        </p>
        <p sizePriority="7">
            Nota2: A <i>tag</i> LIGA oferece uma hiperligação para a <u>wikipedia</u> do TERMO dado como atributo.<br/>
            Existem casos onde a hiperligação devolve <b>Titulo não encontrado</b> devido á má formatação do atributo.
        </p>
        
    </abstract>
    <footer>
        <deliverables>
            <ref link="arq.xml" type="XML"> Arquivo de arqueossitios </ref>
            <ref link="arq.xsl" type="XSL"> Stylesheet para a tradução para um site em HTML do arquivo de arqueossitios </ref>
            <ref link="arq-auto.dtd" type="DTD"> Schema para validação do arquivo de arqueossitios </ref>
            <ref link="site/index.html" type="HTML"> Indice do site do Arquivo de arqueossitios </ref>
        </deliverables>

        <pubDate>3/11/2020</pubDate>
       
    </footer>
</projectRecord>
