=== HCHexY/DAW2020/TPC2/ProjectRecord.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="projectRecord">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="header"/>
        <xs:element ref="workteam"/>
        <xs:element ref="abstract"/>
        <xs:element ref="footer"/>
      </xs:sequence>
      <xs:attributeGroup ref="attlist.projectRecord"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="header">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dates"/>
        <xs:element ref="titles"/>
        <xs:element ref="supervisor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bigTitle"/>
        <xs:element ref="keyName"/>
        <xs:element ref="title"/>
        <xs:element ref="subtitle"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="bigTitle" type="xs:string"/>
  <xs:element name="keyName" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="subtitle" type="xs:string"/>
  <xs:element name="supervisor">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.supervisor"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dates">
    <xs:complexType>
      <xs:attributeGroup ref="attlist.dates"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.dates">
    <xs:attribute name="begin" use="required"/>
    <xs:attribute name="end" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.supervisor">
    <xs:attribute name="svRef" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.projectRecord">
    <xs:attribute name="id" use="required" type="xs:ID"/>
  </xs:attributeGroup>
  <xs:element name="workteam">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="teammate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="teammate">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.teammate"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.teammate">
    <xs:attribute name="tmmRef" use="required"/>
    <xs:attribute name="numMecan"/>
  </xs:attributeGroup>
  <xs:element name="abstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="b"/>
        <xs:element ref="u"/>
        <xs:element ref="ref"/>
        <xs:element ref="br"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.p"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="i">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="p"/>
        <xs:element ref="b"/>
        <xs:element ref="u"/>
        <xs:element ref="ref"/>
        <xs:element ref="br"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="b">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="p"/>
        <xs:element ref="u"/>
        <xs:element ref="ref"/>
        <xs:element ref="br"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="u">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="b"/>
        <xs:element ref="p"/>
        <xs:element ref="ref"/>
        <xs:element ref="br"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="br">
    <xs:complexType/>
  </xs:element>
  <xs:element name="ref">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="i"/>
        <xs:element ref="b"/>
        <xs:element ref="u"/>
      </xs:choice>
      <xs:attributeGroup ref="attlist.ref"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.ref">
    <xs:attribute name="link" use="required"/>
    <xs:attribute name="type" use="required"/>
  </xs:attributeGroup>
  <xs:attributeGroup name="attlist.p">
    <xs:attribute name="sizePriority" default="5"/>
  </xs:attributeGroup>
  <xs:element name="footer">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="deliverables"/>
        <xs:element ref="pubDate"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="deliverables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ref"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pubDate" type="xs:string"/>
</xs:schema>

=== HCHexY/DAW2020/TPC2/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<projectRecord xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/hc/Desktop/DAW/DAW2020/TPC2/ProjectRecord.xsd" id="ID000">
    <header>
        <dates begin="wLUByg7HyVomGfHcC9H.xNty5Xz" end="bU"/>
        <titles>
            <bigTitle>y_O9OkJ0rQX2kD7gR1IYyeq</bigTitle>
            <keyName>rjFuAe2n6.aN4aIoBqdt</keyName>
            <title>MzgyhhF-0EKxNeCaIPJgrpVl</title>
            <subtitle>J9GkeIIbOayToS8DTXDsrbg-n5Xvtq</subtitle>
        </titles>
        <supervisor svRef="DWpF">
        </supervisor>
    </header>
    <workteam>
        <teammate tmmRef="YZ.f6J" numMecan="hNPl">
        </teammate>
        <teammate tmmRef="cRBQ" numMecan="wsIFXJ3">
        </teammate>
    </workteam>
    <abstract>
        <p sizePriority="5">
            <br/>
            <i>
                <b>
                    <u>
                        <ref link="U9uRaQkBcbmo915-Um">
                        </ref>
                        <ref link="mXhtlWh75-n2nc5F">
                        </ref>
                    </u>
                    <br/>
                </b>
                <b>
                    <u>
                        <br/>
                        <ref link="DS53v.utF3Jm3kO">
                        </ref>
                    </u>
                    <br/>
                </b>
            </i>
        </p>
        <p sizePriority="5">
            <ref link="mndgfcXAPwMVqAji0SQTZ8tgGc">
                <u>
                    <br/>
                    <br/>
                </u>
                <u>
                    <b>
                        <br/>
                        <i>
                            <br/>
                            <br/>
                        </i>
                    </b>
                    <b>
                        <i>
                            <br/>
                            <br/>
                        </i>
                        <br/>
                    </b>
                </u>
            </ref>
            <ref link="Y..">
                <i>
                    <br/>
                    <u>
                        <br/>
                        <br/>
                    </u>
                </i>
                <u>
                    <i>
                        <br/>
                        <b>
                            <br/>
                            <br/>
                        </b>
                    </i>
                    <b>
                        <i>
                            <br/>
                            <br/>
                        </i>
                        <i>
                            <br/>
                            <br/>
                        </i>
                    </b>
                </u>
            </ref>
        </p>
    </abstract>
    <footer>
        <deliverables>
            <ref link="KJ3P8G.ehEtVliR34xWBCQs0dJF.G">
                <i>
                    <br/>
                    <br/>
                </i>
                <i>
                    <br/>
                    <u>
                        <br/>
                        <br/>
                    </u>
                </i>
            </ref>
            <ref link="TlyMjwGm4QMSFzqnj">
                <b>
                    <p sizePriority="5">
                        <br/>
                        <br/>
                    </p>
                    <i>
                        <p sizePriority="5">
                            <br/>
                            <u>
                                <br/>
                                <br/>
                            </u>
                        </p>
                        <u>
                            <p sizePriority="5">
                                <br/>
                                <br/>
                            </p>
                            <p sizePriority="5">
                                <br/>
                                <br/>
                            </p>
                        </u>
                    </i>
                </b>
                <b>
                    <p sizePriority="5">
                        <i>
                            <br/>
                            <u>
                                <br/>
                                <br/>
                            </u>
                        </i>
                        <u>
                            <br/>
                            <i>
                                <br/>
                                <br/>
                            </i>
                        </u>
                    </p>
                    <u>
                        <p sizePriority="5">
                            <br/>
                            <br/>
                        </p>
                        <p sizePriority="5">
                            <br/>
                            <i>
                                <br/>
                                <br/>
                            </i>
                        </p>
                    </u>
                </b>
            </ref>
        </deliverables>
        <pubDate>AHwbtRg0OJHKdMXU</pubDate>
    </footer>
</projectRecord>
